[workspace]
members = ["flite", "runtime", "simple-pallet"]
resolver = "2"

[workspace.package]
edition = "2021"

[patch.crates-io]
"polkadot-sdk" = { path = "../polkadot-sdk-2/umbrella", version = "0.1.0" }
